set_property PACKAGE_PIN V17 [get_ports {a0}]
set_property IOSTANDARD LVCMOS33 [get_ports {a0}]
set_property PACKAGE_PIN V16 [get_ports {a1}]
set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN W16 [get_ports {a2}]
set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN W17 [get_ports {a3}]
set_property IOSTANDARD LVCMOS33 [get_ports {a3}]

set_property PACKAGE_PIN W15 [get_ports {b0}]
set_property IOSTANDARD LVCMOS33 [get_ports {b0}]
set_property PACKAGE_PIN V15 [get_ports {b1}]
set_property IOSTANDARD LVCMOS33 [get_ports {b1}]
set_property PACKAGE_PIN W14 [get_ports {b2}]
set_property IOSTANDARD LVCMOS33 [get_ports {b2}]
set_property PACKAGE_PIN W13 [get_ports {b3}]
set_property IOSTANDARD LVCMOS33 [get_ports {b3}]

set_property PACKAGE_PIN W2 [get_ports {d0}]
set_property IOSTANDARD LVCMOS33 [get_ports {d0}]
set_property PACKAGE_PIN U1 [get_ports {d1}]
set_property IOSTANDARD LVCMOS33 [get_ports {d1}]
set_property PACKAGE_PIN T1 [get_ports {d2}]
set_property IOSTANDARD LVCMOS33 [get_ports {d2}]

set_property PACKAGE_PIN R2 [get_ports {en}]
set_property IOSTANDARD LVCMOS33 [get_ports {en}]

set_property PACKAGE_PIN U16 [get_ports {Y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[0]}]
set_property PACKAGE_PIN E19 [get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[1]}]
set_property PACKAGE_PIN U19 [get_ports {Y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[2]}]
set_property PACKAGE_PIN V19 [get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Y[3]}]

set_property PACKAGE_PIN W18 [get_ports {err}]
set_property IOSTANDARD LVCMOS33 [get_ports {err}]
